### ISSUE TITLE
Critical Bug in URL Parsing: Mishandling of Redirected YouTube Links with &feature=youtu.be Query Parameter

### ISSUE THREAD

**Issue by hrolfurinn** [AxelThorAsp/AxelThorAsp.github.io#3]
It’s really concerning that this hasn't been caught yet, but there’s a fundamental flaw in your URL parsing logic when it comes to handling redirected YouTube links. Specifically, if someone copies the shortened YouTube link (youtu.be), pastes it into a browser, and then immediately copies the first redirected link, the URL will still have the &feature=youtu.be query parameter appended to it.

Now, here’s the issue: the code doesn’t account for this at all. Instead, it treats the URL as if it’s still in the shortened format, just because of the presence of "youtu.be" in the query string, which is incredibly short-sighted.

This is the kind of mistake that undermines confidence in the entire flow. It’s bad enough that the code lacks a robust handling of query parameters, but this particular oversight shows a failure to consider how users might interact with links across different contexts. We can’t assume every user is working with pristine URLs all the time.

Steps to Reproduce:

    Copy a YouTube share link (the form youtu.be/someVideoId).
    Paste it into a browser and allow the URL to redirect to the canonical YouTube link (e.g., https://www.youtube.com/watch?v=someVideoId&feature=youtu.be).
    Before the query parameter is stripped away, copy this redirected URL.
    Paste the URL into the input field of your application.

At this point, the code misinterprets the link, treating it as though it’s still shortened, and thus fails to embed the video correctly.

Expected Behavior:

The program should recognize the canonical URL despite the presence of the &feature=youtu.be query parameter and correctly extract the video ID.

Actual Behavior:

The application incorrectly assumes the link is still in its shortened form, leading to a failure in embedding the video.

This is a glaring omission that needs to be addressed immediately. Proper handling of query parameters is a basic expectation when parsing URLs, and this bug reveals a deeper flaw in how edge cases are considered—or rather, not considered.

**Comment by AxelThorAsp** [comment]
Thanks for flagging this. You're absolutely right—this is an oversight in the URL parsing logic, and it should have been caught earlier.

The current approach to handling YouTube links, especially after redirection, is inadequate. Treating URLs as if they're still in shortened form simply because "youtu.be" appears in the query string is a mistake, and I agree it undermines confidence in the logic. We should not be making such basic assumptions about the structure of user-provided URLs.

This flaw highlights a larger issue with how the code handles query parameters in general. Users aren't always working with clean, pristine URLs, and it's unrealistic to assume that they are. I'll be fixing this by:

Ensuring proper handling of redirected YouTube links, regardless of query parameters like &feature=youtu.be.
Removing the faulty assumption that the presence of "youtu.be" in the query string indicates a shortened URL.
Implementing more robust query parameter parsing to prevent similar issues from happening in the future.


### **Key Changes:**

Identify Redirected Links: We check for the presence of "youtu.be" and ensure we extract the video ID correctly without being misled by query parameters.
Clean Handling of Query Parameters: When a standard YouTube URL is provided, we strip any additional query parameters to return a clean URL.
**Error Handling:** 
We introduce error handling to catch invalid URLs instead of making assumptions.
This should prevent any confusion in the future and ensure our URL parsing logic is robust enough to handle various user inputs. I'll prioritize this fix and provide an update shortly. 

### Roadmap and Introducing Rust
**Looking ahead, we plan to enhance the robustness and performance of our codebase, and part of that strategy involves integrating Rust into our stack.** Rust offers several advantages:

Performance: Rust is known for its speed and efficiency, which can lead to faster execution times for computationally intensive tasks.
**Safety**: With its strict compile-time checks, Rust helps prevent many common bugs related to memory management, leading to more stable applications.
Interoperability: We can gradually introduce Rust modules alongside our existing code, allowing us to leverage Rust's strengths without requiring a complete rewrite of the codebase.
**Next Steps**
Implement the proposed fix for the URL parsing logic to handle redirected YouTube links effectively.
Begin planning the integration of Rust into our stack, starting with modules that could benefit most from Rust’s performance and safety features.
This roadmap not only aims to address current issues but also positions us for future scalability and maintainability. I’ll prioritize the URL parsing fix and will keep everyone updated on our progress with Rust integration. Thanks again for bringing this to my attention!
